spring.application.teacherName=JpaCrudMapingAll

spring.datasource.maspring.datasource.url=jdbc:mysql://localhost:3306/jpa_demo?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Tejas@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
