spring.application.name=Jpa03

spring.datasource.url = jdbc:mysql://localhost:3306/jpast
spring.datasource.username = root
spring.datasource.password = Tejas@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
